CREATE TABLE IF NOT EXISTS `#_jukebox_artists` (
    `id` int(10) NOT NULL AUTO_INCREMENT,

  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `#_jukebox_songs` (
    `id` int(10) NOT NULL AUTO_INCREMENT,

  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `#_jukebox_genre` (
    `id` int(10) NOT NULL AUTO_INCREMENT,

  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `#_jukebox_hosts` (
    `id` int(10) NOT NULL AUTO_INCREMENT,

  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `#_jukebox_performance` (
    `id` int(10) NOT NULL AUTO_INCREMENT,

  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `#_jukebox_solo_artists` (
    `id` int(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `firstname` VARCHAR(255),

  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `#_jukebox_bands` (
    `id` int(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,

  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `#_jukebox_cooperations` (
    `id` int(10) NOT NULL UNIQUE,
    `member` int(10) NOT NULL,
    `type` ENUM('band', 'solo'),

  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


